# Generated by Django 4.2.6 on 2023-10-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRRdb',
            fields=[
                ('slID', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('month_year', models.IntegerField()),
                ('datesExcluded', models.TextField(blank=True, null=True)),
                ('numberOfDays', models.IntegerField()),
                ('leadCount', models.IntegerField()),
                ('expectedDrr', models.IntegerField()),
                ('lastUpdatedDate', models.DateField(auto_now=True)),
                ('lastUpdatedTime', models.TimeField(auto_now=True)),
            ],
        ),
    ]
